### ISSUE TITLE
Packing javascsript into single bundlle

### ISSUE THREAD

**Issue by edmundophie** [ktsn/vue-auto-routing#1]
Because of some circumstances, I need to deploy my vue project into a single bundle javascript file.

Before using [vue-cli-plugin-auto-routing](https://github.com/ktsn/vue-cli-plugin-auto-routing), I was able to pack my javascript into a single bundle.js using the following `vue.config.js`:
![image](https://user-images.githubusercontent.com/7218395/43318432-58452d4a-91d3-11e8-9163-26199f3f9e77.png)

Now, after installing vue-cli-plugin-auto-routing, I unable to find a way to make my js packed into a single bundle.
I suspect that the webpack plugn (VueAutoRutingPlugin ) is the cause of this.

Is there any way to workaround this problem?

**Comment by ktsn** [comment]
This is because of dynamic import which webpack split the chunks of imported code.
I just published vue-route-generator v0.2.1 and vue-auto-routing v0.2.0 which have `dynamicImport: false` option to avoid splitting chunks.

**Comment by edmundophie** [comment]
The issue has been fixed for the pages' javascript.
But it seems that for each layout it still creates a separate javascript chunk.

![image](https://user-images.githubusercontent.com/7218395/43375063-69df4ea0-93e5-11e8-9e52-fa30b6b622c6.png)

**Comment by ktsn** [comment]
Yeah, you need to modify router-layout callback not to use dynamic import.

**Comment by edmundophie** [comment]
I'm not sure how to achieve that.

Previously this is how the sample code 
```
import { createRouterLayout } from 'vue-router-layout'

// Create <RouterLayout> component.
const RouterLayout = createRouterLayout(layout => {
  // Resolves a layout component with layout type string.
  return import('@/layouts/' + layout + '.vue')
})
```
What do I need to change in the code above?

**Comment by ktsn** [comment]
I guess it wouldn't be splitted when you use `require` expression

```js
import { createRouterLayout } from 'vue-router-layout'

const RouterLayout = createRouterLayout(layout => {
  return Promise.resolve(require('@/layouts/' + layout + '.vue').default)
})
```
