### ISSUE TITLE
Document how to replace app.vue/main.js

### ISSUE THREAD

**Issue by ndarilek** [ktsn/vue-auto-routing#3]
Sorry if this is obvious and I'm missing it, but once added to the project, what am I supposed to do in src/main.js to use the default layout and this router, vs. the vue-cli defaults? If I just add the plugin and view my app, nothing appears to be different. Presumably I have to load a different component instead of App.vue, or modify App.vue to display the router component rather than the contents of pages/index.vue.

Thanks for creating this. Looking forward to using familiar Nuxt conventions in vue-cli apps.

**Comment by ktsn** [comment]
You should use [vue-cli-plugin-auto-routing](https://github.com/ktsn/vue-cli-plugin-auto-routing) when you use vue-cli and it'll set up the files for you.

**Comment by ndarilek** [comment]
Right, but what isn't obvious to me, particularly as I transition from 
Nuxt to Vue-cli, is that the router plugin isn't enabled in default 
creates. I.e.:


`vue create myproject`


doesn't enable the router by default, and doesn't show it as an option 
unless the manual option is selected and the router is enabled.


I think it might be useful to mention that somewhere for folks like me 
who thought the router was enabled by default in vue-cli.


Thanks.

**Comment by ktsn** [comment]
Well, router related codes will be added by vue-cli-plugin-auto-routing, in any case whether you have such code in existing project. I'm afraid I'm not sure what is unobvious thing for you still...
