### ISSUE TITLE
path problem in Quasar project

### ISSUE THREAD

**Issue by tanthammar** [ktsn/vue-auto-routing#32]
I am using this in a Quasar project.
With the help from you I _almost_ got it working but there is something wrong with the path.

in ` quasar.conf.js`
```
const VueAutoRoutingPlugin = require('vue-auto-routing/lib/webpack-plugin')
const path = require('path')
module.exports = function (ctx) {
  return {
    build: {
      cfg.plugins = cfg.plugins || []
        cfg.plugins.push(new VueAutoRoutingPlugin({
          pages: path.resolve(__dirname, 'src/pages'),
          importPrefix: '@/pages/'
        }))
    }
  }
}
```

Error:
```                                                                                                                                                 
These dependencies were not found:
* @/pages/Account.vue in ./node_modules/vue-auto-routing/index.js
* @/pages/Dashboard.vue in ./node_modules/vue-auto-routing/index.js
 // many more pages
```

All of these gives the same compilation error
```
pages: path.resolve(__dirname, './src/pages'),
pages: path.resolve(__dirname, 'src/pages'),
pages: 'src/pages',
```

This gives *no* compilation errors but the SPA is *blank* and *no routes* are generated *no errors in console*
`pages: '../../src/pages',`

**Comment by ktsn** [comment]
Could you provide a reproduction as like example GitHub project so that I can look into it?

**Comment by tanthammar** [comment]
I'll set up a test project.

**Comment by tanthammar** [comment]
I created a private repo and sent you an invitation link. The read me explains setup.
repo: vue-auto-routing-quasar-path-issue

**Comment by ktsn** [comment]
I looked into it:

1. `pages: '../../src/pages'` is not correct, `pages: path.resolve(__dirname, 'src/pages')` is actually correct one.
2. The dependencies not found error is because quasar does not have the alias `@/`. You need to rewrite `importPrefix` option to `pages/` which is quasar alias to pages directory.

**Comment by tanthammar** [comment]
Magic support. 
Yes, now the routes are generated
But the SPA is blank. 
(try quasar dev)
My original `routes/routes.js` loads the layout, can I register this in another way?
```
path: '/',
    component: () => import('layouts/MyLayout.vue'),
children: [
      { path: '', component: () => import('pages/Index.vue') }
     // and more
    ]
```

**Comment by ktsn** [comment]
Because the page component file is like ‘pages/Index.vue’, the generated route is `/Index` (case-sensitive). You need to rename your page components to actual path name, that is, lower case `pages/index.vue` and so on.

**Comment by ktsn** [comment]
To add layout, you may want to install [vue-router-layout](https://github.com/ktsn/vue-router-layout) and set up the router file with it.

**Comment by tanthammar** [comment]
Ok, slowly getting there.

Tried to implement vue-router-layout
```
Error: Injection "layout" not found
```

My `router/index.js` now looks like this
```js
import routes from 'vue-auto-routing'

import Vue from 'vue'
import VueRouter from 'vue-router'
import { createRouterLayout } from 'vue-router-layout'

// Create <RouterLayout> component.
const path = require('path')
const RouterLayout = createRouterLayout(layout => {
  // Resolves a layout component with layout type string.
  return import(path.resolve(__dirname, 'src/layouts/') + layout + '.vue')
})

// import routes from './routes'

Vue.use(VueRouter)

/*
 * If not building with SSR mode, you can
 * directly export the Router instantiation
 */

export default function (/* { store, ssrContext } */) {
  const Router = new VueRouter({
    scrollBehavior: () => ({ y: 0 }),
    path: '/',
    component: RouterLayout,
    routes,
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  })

  return Router
}
```
Folder structure
```
src/
   layouts/
        MyLayout.vue
   pages/
        index.vue
```

in `pages/index.vue`
```js
export default {
  name: 'index',
  layout: 'MyLayout'
}
```

in `layout/MyLayout.vue`
```js
export default {
  name: 'MyLayout',
}
```

**Comment by ktsn** [comment]
You can't use `path` module as it's running on browser so change it to:

```js
const RouterLayout = createRouterLayout(layout => {
  return import('layouts/' + layout + '.vue')
})
```

And your router option needs to be rewritten:

```js
  const Router = new VueRouter({
    scrollBehavior: () => ({ y: 0 }),
    routes: [
      {
        path: '/',
        component: RouterLayout,
        children: routes
      }
    ],
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  })
```

**Comment by SacDin** [comment]
Hi @tanthammar 
Did you find any solution for link problem ?

**Comment by tanthammar** [comment]
No I was unable to integrate this to Quasar, but I posted a feature request with them. 
https://github.com/quasarframework/quasar/issues/5378

**Comment by rheritahiana** [comment]
it may be late but i found a solution to make vue-auto-routing (https://github.com/ktsn/vue-auto-routing)  work with quasar.
in quasar.conf put these lines:
`const VueAutoRoutingPlugin = require("vue-auto-routing/lib/webpack-plugin");
const path = require("path");`
`   build: {
      vueRouterMode: "hash", // available values: 'hash', 'history'
      extendWebpack(cfg, { isServer, isClient }) {
        cfg.plugins = cfg.plugins || [];
        cfg.plugins.push(
          new VueAutoRoutingPlugin({
            path: '/',
            pages: path.resolve(__dirname, 'src/pages'),
            importPrefix: "src/pages/"
          })
        );
      },

     
      chainWebpack(/* chain */) {
        //
      }
    },`
And then in ./src/router/index.js
`import Vue from 'vue'
import VueRouter from 'vue-router'
import routes from 'vue-auto-routing'
//import routes from './routes'

Vue.use(VueRouter)


export default function (/* { store, ssrContext } */) {
 /*  const Router = new VueRouter({
    scrollBehavior: () => ({ x: 0, y: 0 }),
    routes,

    // Leave these as they are and change in quasar.conf.js instead!
    // quasar.conf.js -> build -> vueRouterMode
    // quasar.conf.js -> build -> publicPath
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE
  }); */

  const Router = new VueRouter({
    scrollBehavior: () => ({ x: 0, y: 0 }),
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE,
    routes: [
      ...routes,
      {
        path: "/",
        component: () => import("src/pages/Index.vue"),
      },
    ],
  });

  return Router
}`
Then you just have to move the content of .src/Layouts/MainLayout.vue to .src/App.vue and it works.
