### ISSUE TITLE
storybook内でエラーが出ます

### ISSUE THREAD

**Issue by k-okina** [ktsn/vue-auto-routing#4]

**Comment by ktsn** [comment]
Please provide following things when you report a bug. I cannot do anything if you don't provide concrete information.

- a minimal / self-contained reproduction
- step to reproduce it
- error message you are seeing
- expected behaviour

**Comment by k-okina** [comment]
ダイナミックインポートの部分でエラーが出ていました。
しかし、単純にstorybookのwebpackの設定と大分差分が出ていたので、その部分を修正すれば治る気がするので、一旦クローズさせていただきます。
