### ISSUE TITLE
<route-meta> Error will stop webpack watch mode

### ISSUE THREAD

**Issue by fangbinwei** [ktsn/vue-auto-routing#56]
Hello friend,

Thanks your vue-cli-plugin very much! I encountered a small problem if there is a error in `<route-meta>`

### Steps

I run project by `vue-cli-service serve`, so webpack run in watch mode.

I added some meta json in `.vue` file, but if the json have some error, the webpack will exit watch mode. The console will stop at ` WAIT  Compiling...`

if you need reproduction for convenience, [here](https://github.com/fangbinwei/auto-routing-issue), just run project, and modify the `<route-meta>` of `about.vue`.

### What is actually happening?
It seems that `watchRun hook` emit error, then `wachRun hook callback` catch this error and execute `failed hook`. After `failed hook` is executed, webpack will exit watch mode. [The releated code](https://github.com/webpack/webpack/blob/45ecebc9f0486c43efc7b56f2c31426d94a55264/lib/Watching.js#L89-L97) of webpack. 

maybe these code can solve the problem

```diff
---        compiler.hooks.run.tap(pluginName, generate);
---        compiler.hooks.watchRun.tap(pluginName, generate);
+++        compiler.hooks.thisCompilation.tap(pluginName, compilation => {
+++            try {
+++                generate();
+++            }
+++            catch (err) {
+++                compilation.errors.push(err);
+++            }
+++        });
```

I test these code in project, compilation error will be processed by `@soda/friendly-errors-webpack-plugin` finally. I'm not very sure  `thisCompilation` is the most suitable solution here.

Moreover, if property `error.file` is added, the output of `friendly-errors-webpack-plugin` will be more beatutiful 🤣 , like this
```bash
 ERROR  Failed to compile with 1 errors                                                                           1:58:37 AM

 error  in nest/nest.vue

Invalid json format of <route-meta> content in nest/nest.vue
Unexpected number in JSON at position 25
```

**vue-route-generator**
```ts
interface wrapError extends Error {
  file?: string
}

// ...
        const file = path.join('/')
        const error: wrapError = new Error(
          `Invalid json format of <route-meta> content in ${file}\n` +
            err.message
        );
        error.file = file
        throw error
```

**Comment by ktsn** [comment]
Thank you for reporting this!
Fix has been released in v0.4.1
