### ISSUE TITLE
Maybe it's better to compile TS to ES5 instead of ES2015

### ISSUE THREAD

**Issue by zhanyuzhang** [ktsn/vue-auto-routing#8]
Vue-auto-routing  is an awesome  thing. However,  babel-loader will ignore the files within node_moudles. When we import vue-auto-routing 
into our project, it will encounter a problem on older devices, such as iOS8/9, witch  not supporting  ES2015. I suggest you changing the  `tsconfig.json`,  rewriting  `"target": "es2015"` to `"target": “es5”`. thanks.

**Comment by ktsn** [comment]
`tsconfig.json` in this repo does not affects generated route code because it is for webpack plugin. I've made a change to [vue-route-generator](https://github.com/ktsn/vue-route-generator) not to include ES2015+ code in generated code. You can try vue-auto-routing@0.4.0 for the fix.
